"""Expert configuration data models."""

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class ExpertProposal:
    """AI-proposed expert for research review.

    Generated by TeamComposerAgent based on research topic analysis.
    """
    expert_domain: str  # e.g., "Zero-Knowledge Proofs Expert"
    rationale: str  # Why this expert is needed for this topic
    focus_areas: List[str]  # Specific aspects to review
    suggested_model: str = "claude-opus-4.5"  # Recommended LLM model
    suggested_provider: str = "anthropic"  # Recommended LLM provider


@dataclass
class ExpertConfig:
    """Final configured expert for review workflow.

    Created from ExpertProposal after user review/editing.
    """
    id: str  # Unique identifier (e.g., "zkp-expert")
    name: str  # Display name (e.g., "Zero-Knowledge Proofs Expert")
    domain: str  # Area of expertise
    focus_areas: List[str]  # Specific review focuses
    system_prompt: str = ""  # LLM system prompt for this expert (generated by SpecialistFactory if empty)
    provider: str = "anthropic"  # LLM provider to use
    model: str = "claude-opus-4.5"  # LLM model to use
    fallback: List[Dict[str, str]] = field(default_factory=list)  # [{"provider": ..., "model": ...}]

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        d = {
            "id": self.id,
            "name": self.name,
            "domain": self.domain,
            "focus_areas": self.focus_areas,
            "provider": self.provider,
            "model": self.model
        }
        if self.fallback:
            d["fallback"] = self.fallback
        return d

    @classmethod
    def from_dict(cls, data: dict, system_prompt: str = "") -> "ExpertConfig":
        """Create from dictionary."""
        return cls(
            id=data["id"],
            name=data["name"],
            domain=data["domain"],
            focus_areas=data["focus_areas"],
            system_prompt=system_prompt,
            provider=data.get("provider", "anthropic"),
            model=data.get("model", "claude-opus-4.5"),
            fallback=data.get("fallback", [])
        )
